# Basic Information 
title: Yewon Lee
position: Ph.D. Student
affiliation: University of Washington
email: yewon (at) cs.washington.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
#keywords: minimal academic
#description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
#canonical: https://minimal-light.yyliu.net/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.ca/citations?hl=en&user=gz4p0PkAAAAJ&view_op=list_works&gmla=AJ1KiT2jA-xMvQ6qaijKFoGaUCdwrZR2GtSWiagUh_hppt26bQQMyoJTmkLs3Gk0fFQdNtDxwGPQHjt5cwNixgJO7x1ZxQxbO0jWZfJTVFm3PJ7eiBg9t4O_hQ_4nV8lmcEHvm4
github_link: https://github.com/yewon-lee
linkedin: https://www.linkedin.com/in/leeyewon/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/headshot.jpeg
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png

remote_theme: yaoyao-liu/minimal-light
